"""Fixed character spritesheet layout.

Character spritesheets intentionally do NOT follow the sheets
generated by RPG Maker (RPG Maker has no ``idle`` concept). Every
character file stores its animations natively, following the same
9-row grid, with at most three frames per row:

    row 1: walk down  (3 frames)
    row 2: walk left  (3 frames)
    row 3: walk right (3 frames)
    row 4: walk up    (3 frames)
    row 5: idle down  (2 frames)
    row 6: idle left  (2 frames)
    row 7: idle right (2 frames)
    row 8: idle up    (2 frames)
    row 9: damaged    (3 frames)

Rows holding a two-frame animation simply leave their third cell
empty (fully transparent).

The frame size is derived from the image size: the width always holds
exactly three frames and the height exactly nine rows, so a 144x432
sheet stores 48x48 frames.
"""

from dataclasses import dataclass

COLUMNS = 3
ROWS = 9

# Animation playback defaults used when generating the Godot
# SpriteFrames resource. Walk cycles at a natural pace, idle rows
# loop slowly (they are breathing animations) and the damaged
# reaction plays once at a fast rate.
WALK_FPS = 6.0
IDLE_FPS = 2.0
DAMAGED_FPS = 8.0


@dataclass(frozen=True)
class CharacterAnimationSpec:
    """Static description of one animation row of the layout."""

    name: str
    row: int
    frame_count: int
    speed: float
    loop: bool


CHARACTER_ANIMATIONS: tuple[CharacterAnimationSpec, ...] = (
    CharacterAnimationSpec(
        name="walk-down",
        row=0,
        frame_count=3,
        speed=WALK_FPS,
        loop=True,
    ),
    CharacterAnimationSpec(
        name="walk-left",
        row=1,
        frame_count=3,
        speed=WALK_FPS,
        loop=True,
    ),
    CharacterAnimationSpec(
        name="walk-right",
        row=2,
        frame_count=3,
        speed=WALK_FPS,
        loop=True,
    ),
    CharacterAnimationSpec(
        name="walk-up",
        row=3,
        frame_count=3,
        speed=WALK_FPS,
        loop=True,
    ),
    CharacterAnimationSpec(
        name="idle-down",
        row=4,
        frame_count=2,
        speed=IDLE_FPS,
        loop=True,
    ),
    CharacterAnimationSpec(
        name="idle-left",
        row=5,
        frame_count=2,
        speed=IDLE_FPS,
        loop=True,
    ),
    CharacterAnimationSpec(
        name="idle-right",
        row=6,
        frame_count=2,
        speed=IDLE_FPS,
        loop=True,
    ),
    CharacterAnimationSpec(
        name="idle-up",
        row=7,
        frame_count=2,
        speed=IDLE_FPS,
        loop=True,
    ),
    CharacterAnimationSpec(
        name="damaged",
        row=8,
        frame_count=3,
        speed=DAMAGED_FPS,
        loop=False,
    ),
)

TOTAL_FRAME_COUNT = sum(
    spec.frame_count
    for spec in CHARACTER_ANIMATIONS
)
