"""Generated by scripts/build_exe.ps1 - do not edit by hand.

This module is rewritten on every executable generation. Source-only
runs therefore always see the last generated value.
"""

BUILD_NUMBER = 10