from .a1 import (
    A1_UNIQUE_COMPOSITION_COUNT,
    a1_animation_durations,
    a1_animation_id,
    a1_composition_quarters,
    a1_is_waterfall,
    a1_kind_frames,
    a1_kind_region,
    a1_quarters_from_index,
    a1_shape_quarters,
    a1_source_region,
    a1_unique_compositions,
    a1_unique_tiles,
)
from .a2 import (
    A2_UNIQUE_COMPOSITION_COUNT,
    a2_shape_quarters,
    a2_source_region,
    a2_unique_compositions,
    a2_unique_tiles,
)
from .a3 import (
    A3_UNIQUE_COMPOSITION_COUNT,
    a3_shape_quarters,
    a3_source_region,
    a3_unique_compositions,
    a3_unique_tiles,
)
from .a4 import a4_source_region, a4_unique_tiles
from .composer import (
    QUARTER_SIZE,
    TILE_SIZE,
    QuarterPiece,
    Quarters,
    compose_autotile,
    compose_quarters,
    unfold_autotile,
    unfold_floor_autotile,
    unfold_wall_autotile,
)
from .shapes import (
    FLOOR_AUTOTILE_TABLE,
    WALL_AUTOTILE_TABLE,
    WATERFALL_AUTOTILE_TABLE,
    AutotileShape,
)
from .unique import unique_tiles

__all__ = [
    "A1_UNIQUE_COMPOSITION_COUNT",
    "A2_UNIQUE_COMPOSITION_COUNT",
    "A3_UNIQUE_COMPOSITION_COUNT",
    "FLOOR_AUTOTILE_TABLE",
    "QUARTER_SIZE",
    "TILE_SIZE",
    "WALL_AUTOTILE_TABLE",
    "WATERFALL_AUTOTILE_TABLE",
    "AutotileShape",
    "QuarterPiece",
    "Quarters",
    "a1_animation_durations",
    "a1_animation_id",
    "a1_composition_quarters",
    "a1_is_waterfall",
    "a1_kind_frames",
    "a1_kind_region",
    "a1_quarters_from_index",
    "a1_shape_quarters",
    "a1_source_region",
    "a1_unique_compositions",
    "a1_unique_tiles",
    "a2_shape_quarters",
    "a2_source_region",
    "a2_unique_compositions",
    "a2_unique_tiles",
    "a3_shape_quarters",
    "a3_source_region",
    "a3_unique_compositions",
    "a3_unique_tiles",
    "a4_source_region",
    "a4_unique_tiles",
    "compose_autotile",
    "compose_quarters",
    "unfold_autotile",
    "unfold_floor_autotile",
    "unfold_wall_autotile",
    "unique_tiles",
]
