# Build the standalone Windows executable.
#
# Usage (from the repository root):
#   powershell -ExecutionPolicy Bypass -File scripts\build_exe.ps1
#
# Prerequisite: the build extra must be installed first:
#   pip install -e ".[build]"
#
# Every run increments the numeric `build` entry of the
# [tool.rpgmaker2godot] table in pyproject.toml, stamps it into
# src/rpgmaker2godot/build_info.py (read by the CLI banner), then
# rebuilds dist\rpgmaker2godot.exe.

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$pyprojectPath = Join-Path $root "pyproject.toml"
$buildInfoPath = Join-Path $root "src\rpgmaker2godot\build_info.py"

Push-Location $root

try {
    # ------------------------------------------------------------
    # Increment the build counter in pyproject.toml.
    # ------------------------------------------------------------
    $content = [System.IO.File]::ReadAllText($pyprojectPath)
    $newline = if ($content.Contains("`r`n")) { "`r`n" } else { "`n" }

    # The counter lives in the [tool.rpgmaker2godot] table: PEP 621
    # reserves the keys of [project], and setuptools would reject a
    # custom entry there. This is the only `build = <number>` line in
    # the file (the `build` extra in [project.optional-dependencies]
    # holds a list, so it cannot match).
    $buildMatch = [regex]::Match(
        $content,
        '(?m)^(?<indent>[ ]*)build[ ]*=[ ]*(?<number>\d+)[ ]*$'
    )

    if ($buildMatch.Success) {
        $number = [int]$buildMatch.Groups["number"].Value + 1
        $line = $buildMatch.Groups["indent"].Value + "build = $number"
        $content = $content.Remove($buildMatch.Index, $buildMatch.Length)
        $content = $content.Insert($buildMatch.Index, $line)
    }
    else {
        # First generation ever: append the dedicated table at the
        # end of the file.
        $number = 1
        $section = @'
# Numeric counter incremented by scripts/build_exe.ps1 on every
# generated executable; displayed in the CLI banner after the
# version (e.g. "rpgmaker2godot v0.1.0 build 12").
#
# Kept in a [tool.*] table on purpose: PEP 621 reserves the keys of
# [project], and setuptools rejects any custom entry found there.
[tool.rpgmaker2godot]
build = NUMBER_PLACEHOLDER
'@
        $section = $section.Replace("NUMBER_PLACEHOLDER", "$number")
        $content = $content.TrimEnd() + $newline + $newline + $section + $newline
    }

    # WriteAllText keeps UTF-8 without BOM, which tomllib requires.
    [System.IO.File]::WriteAllText($pyprojectPath, $content)

    # ------------------------------------------------------------
    # Stamp the runtime module read by the CLI banner.
    # ------------------------------------------------------------
    $stamp = @'
"""Generated by scripts/build_exe.ps1 - do not edit by hand.

This module is rewritten on every executable generation. Source-only
runs therefore always see the last generated value.
"""

BUILD_NUMBER = NUMBER_PLACEHOLDER
'@
    $stamp = $stamp.Replace("NUMBER_PLACEHOLDER", "$number")
    [System.IO.File]::WriteAllText($buildInfoPath, $stamp)

    Write-Host "Build number: $number"

    # ------------------------------------------------------------
    # Generate the executable.
    # ------------------------------------------------------------
    python -m PyInstaller --clean --noconfirm rpgmaker2godot.spec

    if ($LASTEXITCODE -ne 0) {
        throw "PyInstaller failed with exit code $LASTEXITCODE"
    }

    Write-Host ""
    Write-Host "Built: $(Join-Path $root 'dist\rpgmaker2godot.exe') (build $number)"
}
finally {
    Pop-Location
}