# Build the standalone Windows executable.
#
# Usage (from the repository root):
#   powershell -ExecutionPolicy Bypass -File scripts\build_exe.ps1
#
# Prerequisite: the build extra must be installed first:
#   pip install -e ".[build]"
#
# Every run increments the numeric `build` entry of the
# [tool.rpgmaker2godot] table in pyproject.toml, stamps it into
# src/rpgmaker2godot/build_info.py (read by the CLI banner), rebuilds
# dist\rpgmaker2godot.exe, then packages the release archive
# (zip + SHA256 checksum) into dist\.

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$pyprojectPath = Join-Path $root "pyproject.toml"
$buildInfoPath = Join-Path $root "src\rpgmaker2godot\build_info.py"

Push-Location $root

try {
    # ------------------------------------------------------------
    # Increment the build counter in pyproject.toml.
    # ------------------------------------------------------------
    $content = [System.IO.File]::ReadAllText($pyprojectPath)
    $newline = if ($content.Contains("`r`n")) { "`r`n" } else { "`n" }

    # The counter lives in the [tool.rpgmaker2godot] table: PEP 621
    # reserves the keys of [project], and setuptools would reject a
    # custom entry there. This is the only `build = <number>` line in
    # the file (the `build` extra in [project.optional-dependencies]
    # holds a list, so it cannot match).
    #
    # The `\r?` before `$` makes the pattern match CRLF files too:
    # .NET's `$` matches at the `\n`, and a trailing carriage-return
    # would otherwise stay inside the line and break `[ ]*$`.
    $buildMatch = [regex]::Match(
        $content,
        '(?m)^(?<indent>[ ]*)build[ ]*=[ ]*(?<number>\d+)[ ]*\r?$'
    )

    if ($buildMatch.Success) {
        $number = [int]$buildMatch.Groups["number"].Value + 1
        $line = $buildMatch.Groups["indent"].Value + "build = $number"
        $content = $content.Remove($buildMatch.Index, $buildMatch.Length)
        $content = $content.Insert($buildMatch.Index, $line)
    }
    else {
        # First generation ever: append the dedicated table at the
        # end of the file.
        $number = 1
        $section = @'
# Numeric counter incremented by scripts/build_exe.ps1 on every
# generated executable; displayed in the CLI banner after the
# version (e.g. "rpgmaker2godot v0.1.0 build 12").
#
# Kept in a [tool.*] table on purpose: PEP 621 reserves the keys of
# [project], and setuptools rejects any custom entry found there.
[tool.rpgmaker2godot]
build = NUMBER_PLACEHOLDER
'@
        $section = $section.Replace("NUMBER_PLACEHOLDER", "$number")
        $content = $content.TrimEnd() + $newline + $newline + $section + $newline
    }

    # WriteAllText keeps UTF-8 without BOM, which tomllib requires.
    [System.IO.File]::WriteAllText($pyprojectPath, $content)

    # ------------------------------------------------------------
    # Stamp the runtime module read by the CLI banner.
    # ------------------------------------------------------------
    $stamp = @'
"""Generated by scripts/build_exe.ps1 - do not edit by hand.

This module is rewritten on every executable generation. Source-only
runs therefore always see the last generated value.
"""

BUILD_NUMBER = NUMBER_PLACEHOLDER
'@
    $stamp = $stamp.Replace("NUMBER_PLACEHOLDER", "$number")
    [System.IO.File]::WriteAllText($buildInfoPath, $stamp)

    Write-Host "Build number: $number"

    # ------------------------------------------------------------
    # Generate the executable.
    # ------------------------------------------------------------
    python -m PyInstaller --clean --noconfirm rpgmaker2godot.spec

    if ($LASTEXITCODE -ne 0) {
        throw "PyInstaller failed with exit code $LASTEXITCODE"
    }

    # ------------------------------------------------------------
    # Package the release archive (zip + SHA256) in dist\.
    # ------------------------------------------------------------
    # The `version` is read back from the (already updated)
    # pyproject.toml content; `$number` is the freshly incremented
    # build counter. The archive is named after the version and
    # build so it can be attached to a GitHub release as-is.
    $versionMatch = [regex]::Match(
        $content,
        '(?m)^[ ]*version[ ]*=[ ]*"([^"]+)"[ ]*\r?$'
    )

    if (-not $versionMatch.Success) {
        throw "Cannot locate the 'version' entry in pyproject.toml."
    }

    $version = $versionMatch.Groups[1].Value
    $distDir = Join-Path $root "dist"
    $releaseBaseName = "RpgMaker2Godot-win-x64-v${version}${number}"
    $zipPath = Join-Path $distDir "$releaseBaseName.zip"
    $shaPath = "$zipPath.sha256"

    # Stage the archive contents: the Windows executable plus any
    # future assets (sample tilesets, docs, ...). Add them here.
    $stagingDir = Join-Path $env:TEMP "rpgmaker2godot-release-$releaseBaseName"
    if (Test-Path $stagingDir) {
        Remove-Item $stagingDir -Recurse -Force
    }
    New-Item -ItemType Directory -Path $stagingDir | Out-Null

    Copy-Item (Join-Path $distDir "rpgmaker2godot.exe") (Join-Path $stagingDir "rpgmaker2godot.exe")

    # Drop a fresh archive/sum for this version+build, then zip.
    Remove-Item $zipPath -ErrorAction SilentlyContinue
    Remove-Item $shaPath -ErrorAction SilentlyContinue

    Compress-Archive -Path "$stagingDir\*" -DestinationPath $zipPath

    # SHA256 in <hash>  <filename> format (uppercase, standard Git).
    $sha256 = (Get-FileHash -Algorithm SHA256 -Path $zipPath).Hash
    "$sha256  $releaseBaseName.zip" | Set-Content -Path $shaPath -Encoding ascii

    Remove-Item $stagingDir -Recurse -Force

    Write-Host ""
    Write-Host "Built: $(Join-Path $root 'dist\rpgmaker2godot.exe') (build $number)"
    Write-Host "Release: $releaseBaseName.zip"
    Write-Host "SHA256:  $sha256  ($releaseBaseName.zip.sha256)"
}
finally {
    Pop-Location
}