# Build the standalone Windows executable.
#
# Usage (from the repository root):
#   powershell -ExecutionPolicy Bypass -File scripts\build_exe.ps1
#
# Prerequisite: the build extra must be installed first:
#   pip install -e ".[build]"
#
# Every run increments the numeric `build` entry of the [project]
# section in pyproject.toml, stamps it into
# src/rpgmaker2godot/build_info.py (read by the CLI banner), then
# rebuilds dist\rpgmaker2godot.exe.

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$pyprojectPath = Join-Path $root "pyproject.toml"
$buildInfoPath = Join-Path $root "src\rpgmaker2godot\build_info.py"

Push-Location $root

try {
    # ------------------------------------------------------------
    # Increment the build counter in pyproject.toml.
    # ------------------------------------------------------------
    $content = [System.IO.File]::ReadAllText($pyprojectPath)
    $newline = if ($content.Contains("`r`n")) { "`r`n" } else { "`n" }

    $buildMatch = [regex]::Match(
        $content,
        '(?m)^(?<indent>[ ]*)build[ ]*=[ ]*(?<number>\d+)[ ]*$'
    )

    if ($buildMatch.Success) {
        $number = [int]$buildMatch.Groups["number"].Value + 1
        $line = $buildMatch.Groups["indent"].Value + "build = $number"
        $content = $content.Remove($buildMatch.Index, $buildMatch.Length)
        $content = $content.Insert($buildMatch.Index, $line)
    }
    else {
        # First generation ever: insert the entry right after the
        # version line of the [project] section.
        $versionMatch = [regex]::Match(
            $content,
            '(?m)^[ ]*version[ ]*=[ ]*"[^"]*"[ ]*$'
        )

        if (-not $versionMatch.Success) {
            throw "Cannot locate the 'version' entry in pyproject.toml."
        }

        $number = 1
        $insertion = $versionMatch.Value +
            $newline +
            $versionMatch.Groups["indent"].Value +
            "build = $number"

        $content = $content.Remove($versionMatch.Index, $versionMatch.Length)
        $content = $content.Insert($versionMatch.Index, $insertion)
    }

    # WriteAllText keeps UTF-8 without BOM, which tomllib requires.
    [System.IO.File]::WriteAllText($pyprojectPath, $content)

    # ------------------------------------------------------------
    # Stamp the runtime module read by the CLI banner.
    # ------------------------------------------------------------
    $stamp = @'
"""Generated by scripts/build_exe.ps1 - do not edit by hand.

This module is rewritten on every executable generation. Source-only
runs therefore always see the last generated value.
"""

BUILD_NUMBER = NUMBER_PLACEHOLDER
'@
    $stamp = $stamp.Replace("NUMBER_PLACEHOLDER", "$number")
    [System.IO.File]::WriteAllText($buildInfoPath, $stamp)

    Write-Host "Build number: $number"

    # ------------------------------------------------------------
    # Generate the executable.
    # ------------------------------------------------------------
    python -m PyInstaller --clean --noconfirm rpgmaker2godot.spec

    if ($LASTEXITCODE -ne 0) {
        throw "PyInstaller failed with exit code $LASTEXITCODE"
    }

    Write-Host ""
    Write-Host "Built: $(Join-Path $root 'dist\rpgmaker2godot.exe') (build $number)"
}
finally {
    Pop-Location
}