"""User-facing console messages for the CLI."""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import metadata

from ..build_info import BUILD_NUMBER
from rich.console import Console
from rich.panel import Panel

_PACKAGE_NAME = "rpgmaker2godot"


def display_title(
    message: str,
) -> None:
    """Display a title inside a panel with a blue background.

    The panel is rendered with a bright white text on a blue
    background and a blue border, expanded to the full console
    width.

    Args:
        message: The message to display inside the panel.
    """
    console = Console()

    title = Panel(
        message,
        style="bright_white on blue",  # White text on blue background
        title="",  # Panel title
        border_style="blue",  # Blue border
        expand=True,  # Expand to full width
    )

    console.print("")
    console.print(title)
    console.print("")


def display_program_banner() -> None:
    """Display the program name, version and description as a banner.

    The values are read from the installed package metadata so that
    they always stay in sync with pyproject.toml. When an executable
    has been generated, the numeric build counter is appended after
    the version (e.g. "rpgmaker2godot v0.1.0 build 12").
    """

    try:
        package_metadata = metadata(_PACKAGE_NAME)

        name = package_metadata["Name"]
        version = package_metadata["Version"]
        summary = package_metadata["Summary"] or ""
    except PackageNotFoundError:
        # Running from an uninstalled source tree.
        name = _PACKAGE_NAME
        version = "unknown"
        summary = ""

    title = f"{name} v{version}"

    # The build number only exists once an executable has been
    # generated by scripts/build_exe.ps1.
    if isinstance(BUILD_NUMBER, int) and BUILD_NUMBER > 0:
        title += f" build {BUILD_NUMBER}"

    display_title(f"{title}\n{summary}")